name: Multi-Shell Environment Exercise
on: [push]

jobs:
  multi-shell-job:
    runs-on: windows-latest
    steps:
      - name: Bash - System Information
        shell: bash
        run: uname -a
        
      - name: PowerShell - Computer Information
        shell: pwsh
        run: |
          Get-ComputerInfo
          # $PSVersionTable
          # Get-Host | Select-Object Version
        
      - name: Python - Version Information
        shell: python
        run: |
          import sys
          print(sys.version)
          
      - name: Node.js - Version Information
        shell: node {0}
        run: |
          console.log(process.version)

  directory-navigation:
    runs-on: ubuntu-latest
    steps:
      - name: Create test_folder in /home/runner
        run: mkdir -p /home/runner/test_folder
        
      - name: Create sample.txt file
        run: echo "This is a sample text file created by GitHub Actions" > /home/runner/test_folder/sample.txt
        
      - name: Check file content
        working-directory: /home/runner/test_folder
        run: cat sample.txt